//usuario
export const LOGIN = "LOGIN";
export const RESET_LOGIN = "RESET_LOGIN";
export const REGISTRARSE = "REGISTRARSE";
export const GET_ALL_USUARIOS = "GET_ALL_USUARIOS";
export const GET_USUARIOS_BY_ROL = "GET_USUARIOS_BY_ROL";
export const GET_USER = "GET_USER";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_USER_BY_DNI = "GET_USER_BY_DNI";
export const RESET_USER = "RESET_USER";
export const MODIFICA_USUARIO = "MODIFICA_USUARIO";
export const MODIFICA_CONTRASENA = "MODIFICA_CONTRASENA";
//Articulos
export const LOADING = "LOADING";
export const CREA_ARTICULO = "CREA_ARTICULO";
export const GET_ARTICULOS = "GET_ARTICULOS";
export const GET_ARTICULO = "GET_ARTICULO";
export const GET_ARTICULO_BY_ID = "GET_ARTICULO_BY_ID";
export const GET_ARTICULO_POR_NOMBRE = "GET_ARTICULO_POR_NOMBRE";
export const RESET_ARTICULO = "RESET_ARTICULO";
export const ELIMINA_ARTICULO = "ELIMINA_ARTICULO";
export const MODIFICA_ARTICULO = "MODIFICA_ARTICULO";
export const CREA_ARTICULO_PROVEEDOR = "CREA_ARTICULO_PROVEEDOR";
export const GET_ARTICULOS_PROVEEDOR = "GET_ARTICULOS_PROVEEDOR";
export const AJUSTE_STOCK_SUCCESS = "AJUSTE_STOCK_SUCCESS";
export const GET_HISTORIAL_INVENTARIO_REQUEST = "GET_HISTORIAL_INVENTARIO_REQUEST";
export const GET_HISTORIAL_INVENTARIO_SUCCESS = "GET_HISTORIAL_INVENTARIO_SUCCESS";
export const GET_HISTORIAL_INVENTARIO_FAIL = "GET_HISTORIAL_INVENTARIO_FAIL";
export const CLEAR_HISTORIAL_INVENTARIO_ERROR = "CLEAR_HISTORIAL_INVENTARIO_ERROR";
export const REMITOS_REQUEST = "REMITOS_REQUEST";
export const GET_REMITOS_SUCCESS = "GET_REMITOS_SUCCESS";
export const GET_REMITO_BY_ID_SUCCESS = "GET_REMITO_BY_ID_SUCCESS";
export const CREA_REMITO_SUCCESS = "CREA_REMITO_SUCCESS";
export const REMITOS_FAIL = "REMITOS_FAIL";
export const RECIBOS_REQUEST = "RECIBOS_REQUEST";
export const GET_RECIBOS_SUCCESS = "GET_RECIBOS_SUCCESS";
export const GET_RECIBO_BY_ID_SUCCESS = "GET_RECIBO_BY_ID_SUCCESS";
export const CREA_RECIBO_SUCCESS = "CREA_RECIBO_SUCCESS";
export const RECIBOS_FAIL = "RECIBOS_FAIL";
//Categorias
export const CREA_CATEGORIA = "CREA_CATEGORIA";
export const GET_CATEGORIAS = "GET_CATEGORIAS";

